"""empty message

Revision ID: 1ef9c9fa9d78
Revises: be7e73e70b93
Create Date: 2022-06-10 21:39:23.376809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef9c9fa9d78'
down_revision = 'be7e73e70b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('price', sa.Float(precision=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'price')
    # ### end Alembic commands ###
