"""empty message

Revision ID: 3c05b35293d4
Revises: f853f2aae80d
Create Date: 2022-06-19 16:57:56.911456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c05b35293d4'
down_revision = 'f853f2aae80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('carts', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'user', 'cart', ['carts'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'carts')
    # ### end Alembic commands ###
