"""empty message

Revision ID: 409c10e8f747
Revises: bf120e5be46c
Create Date: 2022-06-20 17:54:20.495952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409c10e8f747'
down_revision = 'bf120e5be46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cartitems_item_fkey', 'cartitems', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cartitems_item_fkey', 'cartitems', 'character', ['item'], ['id'])
    # ### end Alembic commands ###
