"""empty message

Revision ID: 983d9aed4d3d
Revises: 37b9a8e83890
Create Date: 2022-05-30 19:15:53.919820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983d9aed4d3d'
down_revision = '37b9a8e83890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('creator', sa.String(), nullable=True))
    op.create_foreign_key(None, 'character', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'creator')
    # ### end Alembic commands ###
