"""empty message

Revision ID: d6a0ba51b6b4
Revises: 3c05b35293d4
Create Date: 2022-06-19 16:58:55.748542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a0ba51b6b4'
down_revision = '3c05b35293d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('carts', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'cart', ['carts'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'carts')
    # ### end Alembic commands ###
